// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Projeto_Hotelaria.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Model.Clean", b =>
                {
                    b.Property<int>("CleanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("CleanId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Cleans");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("longtext");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Model.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Model.Guest", b =>
                {
                    b.Property<int>("IdGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GuestBirth")
                        .HasColumnType("longtext");

                    b.Property<string>("GuestIdentification")
                        .HasColumnType("longtext");

                    b.Property<string>("GuestName")
                        .HasColumnType("longtext");

                    b.Property<string>("MothersName")
                        .HasColumnType("longtext");

                    b.Property<double>("Payment")
                        .HasColumnType("double");

                    b.HasKey("IdGuest");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.Property<double>("ProductValue")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Model.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GuestIdGuest")
                        .HasColumnType("int");

                    b.Property<int>("IdGuest")
                        .HasColumnType("int");

                    b.HasKey("IdReservation");

                    b.HasIndex("GuestIdGuest");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Model.ReservationRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationIdReservation")
                        .HasColumnType("int");

                    b.Property<int?>("RoomIdRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationIdReservation");

                    b.HasIndex("RoomIdRoom");

                    b.ToTable("ReservationRooms");
                });

            modelBuilder.Entity("Model.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoomDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("RoomFloor")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("longtext");

                    b.Property<double>("RoomValue")
                        .HasColumnType("double");

                    b.HasKey("IdRoom");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Model.Clean", b =>
                {
                    b.HasOne("Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Model.Expense", b =>
                {
                    b.HasOne("Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Model.Reservation", b =>
                {
                    b.HasOne("Model.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestIdGuest");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Model.ReservationRoom", b =>
                {
                    b.HasOne("Model.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationIdReservation");

                    b.HasOne("Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomIdRoom");

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
